#!/bin/bash
# Quick Start Guide for Robot Calibration
# Run this script to see available commands

echo "========================================================================"
echo "  ROBOT CALIBRATION - QUICK START GUIDE"
echo "========================================================================"
echo ""
echo "Available Scripts:"
echo ""
echo "1. Preview Positions (Recommended First)"
echo "   → Check calibration positions without moving robot"
echo "   $ python preview_positions.py"
echo ""
echo "2. Test Single Position"
echo "   → Test one position to verify setup"
echo "   $ python test_single_position.py"
echo ""
echo "3. Run Full Calibration"
echo "   → Automatically move through all 9 positions"
echo "   $ python calibration_automation.py"
echo ""
echo "========================================================================"
echo "  WORKFLOW"
echo "========================================================================"
echo ""
echo "Step 1: Edit calibration_positions.yaml (if needed)"
echo "        - Adjust the 9 calibration positions"
echo "        - Default is a 3x3 grid"
echo ""
echo "Step 2: Preview positions"
echo "        $ python preview_positions.py"
echo ""
echo "Step 3: Test single position (optional)"
echo "        $ python test_single_position.py"
echo ""
echo "Step 4: Run full calibration"
echo "        $ python calibration_automation.py"
echo ""
echo "Step 5: Check output in calibration_data/ folder"
echo "        - YAML files with robot positions and transforms"
echo "        - PNG files with captured images"
echo ""
echo "========================================================================"
echo ""
echo "For detailed documentation, see README.md"
echo ""
